### ISSUE TITLE
Provide a comprehensive demo of the solution

### ISSUE THREAD

**Issue by pedromauricio** [awslabs/aws-connected-vehicle-solution#2]
The current state of the project builds the scaffolding on AWS, but it's still not possible to run a demo on it. This makes it quite hard to get into the solution.

You could improve this by providing a comprehensive demo, including input examples and message types, as well as tutorial documentation.

This would be a great starting point:
AMF303 - Deep Dive into the Connected Vehicle Reference Architecture
https://www.portal.reinvent.awsevents.com/connect/sessionDetail.ww?SESSION_ID=14483

**Comment by shsenior** [comment]
We will be releasing a IoT Device simulator with an automotive module that integrates seamlessly to the the connected vehicle solution in 2018Q2. It will allow you to create a fleet of vehicles that will simulate vehicle telemetry information and publish it to the connected vehicle solution.
